// investa-admin-portal/src/components/common/ApiBaseSwitcher.tsx
import React, { useState } from 'react';
import { useLocalStorage } from '../../hooks/useLocalStorage';

const PRESET_URLS = [
  'http://DESKTOP-DIH7CQH:5235',
  'http://DESKTOP-DIH7CQH:5000',
  'http://localhost:5235',
  'http://localhost:5000'
];

export default function ApiBaseSwitcher() {
  const [apiBase, setApiBase] = useLocalStorage<string>('apiBase', 'http://DESKTOP-DIH7CQH:5235');
  const [open, setOpen] = useState(false);
  const [custom, setCustom] = useState(apiBase);

  function apply(url: string) {
    setApiBase(url.replace(/\/+$/, ''));
    updateRuntime(url);
    setOpen(false);
  }

  function updateRuntime(url: string) {
    try {
      // set global and meta tag for runtime pickup
      (window as any).__INVESTA_API_BASE = url;
      let m = document.querySelector('meta[name="investa-api-base"]');
      if (!m) {
        m = document.createElement('meta');
        m.setAttribute('name', 'investa-api-base');
        document.head.appendChild(m);
      }
      m.setAttribute('content', url);
      console.info('[Admin] API base set to', url);
    } catch (e) {
      console.warn('Failed to set runtime API base', e);
    }
  }

  return (
    <div className="relative">
      <button onClick={() => setOpen(!open)} className="px-2 py-1 rounded bg-slate-800 text-sm text-white hover:bg-slate-700">
        API: {apiBase}
      </button>
      {open && (
        <div className="absolute right-0 mt-2 w-64 bg-white text-slate-900 rounded shadow p-3 z-50">
          <div className="mb-2 text-sm font-semibold">Select API Base</div>
          <div className="space-y-2">
            {PRESET_URLS.map(u => (
              <div key={u} className="flex justify-between items-center">
                <div className="truncate mr-2">{u}</div>
                <button onClick={() => apply(u)} className="text-blue-600 text-sm">Use</button>
              </div>
            ))}
            <div className="border-t pt-2">
              <label className="block text-xs text-slate-500">Custom</label>
              <input value={custom} onChange={e => setCustom(e.target.value)} className="mt-1 w-full rounded border px-2 py-1 text-sm" />
              <div className="flex justify-end mt-2">
                <button onClick={() => apply(custom)} className="text-sm px-2 py-1 bg-blue-600 text-white rounded">Apply</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// investa-client-portal/src/app/components/api-base-switcher/api-base-switcher.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

const PRESETS = ['http://DESKTOP-DIH7CQH:5235', 'http://DESKTOP-DIH7CQH:5000', 'http://localhost:5235'];
const STORAGE_KEY = 'apiBase';

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule],
  selector: 'app-api-base-switcher',
  template: `
    <div class="fixed bottom-4 end-4 z-50">
      <div class="bg-slate-900 text-white rounded-xl shadow p-3 flex items-center gap-3">
        <div class="text-xs">API:</div>
        <div class="text-xs font-mono truncate w-48">{{ current() }}</div>
        <button class="text-xs bg-slate-700 px-2 py-1 rounded" (click)="open.set(!open())">Change</button>
      </div>
      <div *ngIf="open()" class="mt-2 bg-white rounded-lg shadow p-3 w-96 text-sm text-black">
        <div *ngFor="let p of presets" class="flex items-center justify-between py-1">
          <div class="truncate">{{p}}</div>
          <button (click)="apply(p)" class="text-blue-600">Use</button>
        </div>
        <div class="border-t mt-2 pt-2">
          <input [(ngModel)]="custom" placeholder="Custom URL" class="w-full rounded border px-2 py-1" />
          <div class="flex justify-end mt-2">
            <button (click)="apply(custom)" class="px-3 py-1 bg-blue-600 text-white rounded">Apply</button>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class ApiBaseSwitcherComponent {
  presets = PRESETS;
  open = signal(false);
  current = signal<string>(localStorage.getItem(STORAGE_KEY) || 'http://DESKTOP-DIH7CQH:5235');
  custom = '';

  constructor() { }

  apply(url: string | null | undefined) {
    if (!url) return;
    const v = url.replace(/\/+$/, '');
    localStorage.setItem(STORAGE_KEY, v);
    this.current.set(v);
    try {
      (window as any).__INVESTA_API_BASE = v;
      let m = document.querySelector('meta[name="investa-api-base"]');
      if (!m) {
        m = document.createElement('meta');
        m.setAttribute('name', 'investa-api-base');
        document.head.appendChild(m);
      }
      m.setAttribute('content', v);
    } catch (e) {
      // Silently fail - API base switching is optional
    }
    this.open.set(false);
  }
}
